const initialFacilities = [
  {
    id: 'FAC-PHC-001',
    name: 'Rampur Primary Health Centre (PHC)',
    type: 'PHC',
    level: 1,
    village: 'Rampur',
    block: 'Kashipur',
    district: 'Moradabad',
    state: 'Uttar Pradesh',
    coordinates: { lat: 28.8386, lng: 78.7733 },
    distanceKm: 3.2,
    contactNumber: '+91-9876543210',
    doctors: [
      { name: 'Dr. Rajesh Verma', specialty: 'General Physician (MBBS)', available: true, onDutyHours: '08:00 - 16:00' },
      { name: 'Dr. Sunita Sharma', specialty: 'Ayush Medical Officer', available: true, onDutyHours: '09:00 - 17:00' }
    ],
    nursesCount: 4,
    ashaWorkersCount: 8,
    beds: { total: 6, occupied: 3, available: 3 },
    oxygenCylinders: 4,
    diagnosticsAvailable: ['Blood Glucose', 'Rapid Malaria Test', 'Hemoglobin (Hb)', 'Urine Albumin', 'Basic ECG'],
    diagnosticsMissing: ['X-Ray', 'Ultrasound', 'CT Scan', 'ICU'],
    operatingStatus: 'Open',
    currentWaitTimeMins: 20,
    emergencyCapable: false,
    rating: 4.2
  },
  {
    id: 'FAC-CHC-001',
    name: 'Bilari Community Health Centre (CHC)',
    type: 'CHC',
    level: 2,
    village: 'Bilari',
    block: 'Bilari',
    district: 'Moradabad',
    state: 'Uttar Pradesh',
    coordinates: { lat: 28.6258, lng: 78.8025 },
    distanceKm: 14.5,
    contactNumber: '+91-9876543222',
    doctors: [
      { name: 'Dr. Arvind Kumar', specialty: 'General Surgeon (MS)', available: true, onDutyHours: '24x7 Emergency' },
      { name: 'Dr. Priya Saxena', specialty: 'Gynecologist & Obstetrician', available: true, onDutyHours: '09:00 - 18:00' },
      { name: 'Dr. Manoj Tiwari', specialty: 'Pediatrician', available: false, onDutyHours: 'Leave today' },
      { name: 'Dr. Rekha Pal', specialty: 'Anesthetist', available: true, onDutyHours: 'On-Call' }
    ],
    nursesCount: 12,
    ashaWorkersCount: 24,
    beds: { total: 30, occupied: 22, available: 8 },
    oxygenCylinders: 18,
    diagnosticsAvailable: ['Digital X-Ray', 'Complete Blood Count (CBC)', 'Basic Ultrasound', 'ECG', 'Blood Bank Storage', 'Biochemistry'],
    diagnosticsMissing: ['CT Scan', 'MRI', 'Neonatal ICU (NICU) Level 3'],
    operatingStatus: 'Open',
    currentWaitTimeMins: 45,
    emergencyCapable: true,
    rating: 4.5
  },
  {
    id: 'FAC-DH-001',
    name: 'Moradabad District Civil & Trauma Hospital',
    type: 'District Hospital',
    level: 3,
    village: 'Civil Lines',
    block: 'Moradabad Urban',
    district: 'Moradabad',
    state: 'Uttar Pradesh',
    coordinates: { lat: 28.8353, lng: 78.7758 },
    distanceKm: 28.0,
    contactNumber: '+91-591-2412001',
    doctors: [
      { name: 'Dr. K. K. Agarwal', specialty: 'Chief Medical Officer / Cardiologist', available: true, onDutyHours: '24x7' },
      { name: 'Dr. S. K. Gupta', specialty: 'Neuro & Trauma Specialist', available: true, onDutyHours: '24x7' },
      { name: 'Dr. Meenakshi Roy', specialty: 'Critical Care / ICU Incharge', available: true, onDutyHours: '24x7' },
      { name: 'Dr. Tarun Bhatnagar', specialty: 'Senior Orthopedic Surgeon', available: true, onDutyHours: '24x7' }
    ],
    nursesCount: 65,
    ashaWorkersCount: 120,
    beds: { total: 200, occupied: 168, available: 32 },
    oxygenCylinders: 85,
    diagnosticsAvailable: ['CT Scan', 'High-Res Ultrasound', '24x7 Blood Bank', 'Color Doppler', 'Digital X-Ray', 'Pathology Lab', 'ICU Beds (12)', 'NICU (8)'],
    diagnosticsMissing: ['MRI (Under Maintenance)'],
    operatingStatus: 'Open 24x7',
    currentWaitTimeMins: 60,
    emergencyCapable: true,
    rating: 4.7
  },
  {
    id: 'FAC-SC-001',
    name: 'Shivpuri Health & Wellness Sub-Centre',
    type: 'Sub-Centre',
    level: 0,
    village: 'Shivpuri',
    block: 'Kashipur',
    district: 'Moradabad',
    state: 'Uttar Pradesh',
    coordinates: { lat: 28.852, lng: 78.751 },
    distanceKm: 1.5,
    contactNumber: '+91-9876543244',
    doctors: [
      { name: 'ANM Geeta Devi', specialty: 'Community Health Officer (CHO)', available: true, onDutyHours: '09:00 - 15:00' }
    ],
    nursesCount: 2,
    ashaWorkersCount: 4,
    beds: { total: 2, occupied: 1, available: 1 },
    oxygenCylinders: 1,
    diagnosticsAvailable: ['Blood Glucose', 'Pregnancy Strip (Nischay)', 'Blood Pressure Check', 'Rapid Malaria'],
    diagnosticsMissing: ['ECG', 'X-Ray', 'Ultrasound', 'Blood Tests'],
    operatingStatus: 'Open',
    currentWaitTimeMins: 10,
    emergencyCapable: false,
    rating: 4.0
  }
];

const initialDiseases = [
  {
    diseaseId: 'DIS-101',
    diseaseName: 'Malaria (Plasmodium Vivax / Falciparum)',
    category: 'Vector-Borne Infectious',
    description: 'Acute febrile illness caused by Plasmodium parasites transmitted through infected female Anopheles mosquitoes.',
    symptoms: ['High fever with chills', 'Rigor', 'Profuse sweating', 'Headache', 'Body ache', 'Nausea'],
    icdCode: 'B54',
    severityDefault: 'Moderate',
    status: 'Active'
  },
  {
    diseaseId: 'DIS-102',
    diseaseName: 'Acute Gastroenteritis / Dehydration',
    category: 'Gastrointestinal & Waterborne',
    description: 'Infection causing inflammation of the stomach and intestines leading to watery diarrhea and dehydration.',
    symptoms: ['Watery diarrhea', 'Abdominal cramps', 'Vomiting', 'Dry mouth', 'Weakness', 'Mild fever'],
    icdCode: 'A09',
    severityDefault: 'Moderate',
    status: 'Active'
  },
  {
    diseaseId: 'DIS-103',
    diseaseName: 'Dengue Fever',
    category: 'Vector-Borne Viral',
    description: 'Mosquito-borne viral infection causing flu-like illness and potentially lethal complications (severe dengue).',
    symptoms: ['Sudden high fever', 'Severe retro-orbital eye pain', 'Joint pain (Breakbone)', 'Skin rash', 'Low platelets'],
    icdCode: 'A90',
    severityDefault: 'Severe',
    status: 'Active'
  },
  {
    diseaseId: 'DIS-104',
    diseaseName: 'Type 2 Diabetes Mellitus',
    category: 'Chronic Endocrine / Metabolic',
    description: 'Metabolic disorder characterized by hyperglycemia resulting from progressive insulin secretion defect.',
    symptoms: ['Increased thirst (polydipsia)', 'Frequent urination', 'Fatigue', 'Blurry vision', 'Slow-healing sores'],
    icdCode: 'E11',
    severityDefault: 'Moderate',
    status: 'Active'
  },
  {
    diseaseId: 'DIS-105',
    diseaseName: 'Essential Hypertension',
    category: 'Cardiovascular Chronic',
    description: 'Persistent elevation of systemic arterial blood pressure exceeding 140/90 mmHg without identifiable cause.',
    symptoms: ['Occipital morning headache', 'Dizziness', 'Tinnitus', 'Palpitations', 'Often asymptomatic'],
    icdCode: 'I10',
    severityDefault: 'Moderate',
    status: 'Active'
  },
  {
    diseaseId: 'DIS-106',
    diseaseName: 'Upper Respiratory Tract Infection (URTI)',
    category: 'Respiratory Infectious',
    description: 'Contagious viral or bacterial infection of the nasal passage, pharynx, larynx, and major bronchi.',
    symptoms: ['Sore throat', 'Runny nose', 'Nasal congestion', 'Cough', 'Low-grade fever', 'Malaise'],
    icdCode: 'J06.9',
    severityDefault: 'Mild',
    status: 'Active'
  },
  {
    diseaseId: 'DIS-107',
    diseaseName: 'Iron Deficiency Anemia (Maternal / General)',
    category: 'Nutritional / Hematologic',
    description: 'Condition characterized by insufficient healthy red blood cells due to inadequate dietary iron or blood loss.',
    symptoms: ['Extreme fatigue', 'Pale conjunctiva & skin', 'Shortness of breath on exertion', 'Brittle nails', 'Pica'],
    icdCode: 'D50',
    severityDefault: 'Moderate',
    status: 'Active'
  }
];

const initialMedicines = [
  {
    id: 'MED-01',
    name: 'Paracetamol 500mg',
    genericName: 'Paracetamol / Acetaminophen',
    category: 'Antipyretic / Analgesic',
    dosageForm: 'Tablet',
    strength: '500mg',
    manufacturer: 'Karnataka Antibiotics & Pharmaceuticals Ltd (KAPL)',
    batchNumber: 'PCM-2026-A1',
    expiryDate: new Date('2027-08-31'),
    facilityId: 'FAC-PHC-001',
    facilityName: 'Rampur PHC',
    stockQty: 420,
    minThreshold: 100,
    status: 'In Stock',
    unit: 'Strips (10 tabs)'
  },
  {
    id: 'MED-02',
    name: 'Amoxicillin 500mg',
    genericName: 'Amoxicillin Trihydrate',
    category: 'Antibiotic',
    dosageForm: 'Capsule',
    strength: '500mg',
    manufacturer: 'Hindustan Antibiotics Ltd',
    batchNumber: 'AMX-2026-B4',
    expiryDate: new Date('2027-05-15'),
    facilityId: 'FAC-PHC-001',
    facilityName: 'Rampur PHC',
    stockQty: 45,
    minThreshold: 100,
    status: 'Low Stock',
    unit: 'Strips (10 caps)'
  },
  {
    id: 'MED-03',
    name: 'Oral Rehydration Salts (ORS IP)',
    genericName: 'WHO Standard Oral Rehydration Salts',
    category: 'Electrolytes & Hydration',
    dosageForm: 'Powder Sachet',
    strength: '20.5g / 1 Litre Pack',
    manufacturer: 'IDPL India',
    batchNumber: 'ORS-2026-C8',
    expiryDate: new Date('2027-12-31'),
    facilityId: 'FAC-PHC-001',
    facilityName: 'Rampur PHC',
    stockQty: 310,
    minThreshold: 150,
    status: 'In Stock',
    unit: 'Sachets'
  },
  {
    id: 'MED-04',
    name: 'Zinc Sulphate 20mg Dispersible',
    genericName: 'Zinc Sulphate Monohydrate',
    category: 'Micronutrient / Diarrhea Adjunct',
    dosageForm: 'Dispersible Tablet',
    strength: '20mg',
    manufacturer: 'Bengal Chemicals & Pharmaceuticals Ltd',
    batchNumber: 'ZNC-2026-D2',
    expiryDate: new Date('2027-10-31'),
    facilityId: 'FAC-PHC-001',
    facilityName: 'Rampur PHC',
    stockQty: 250,
    minThreshold: 80,
    status: 'In Stock',
    unit: 'Strips (14 tabs)'
  },
  {
    id: 'MED-05',
    name: 'Chloroquine Phosphate 250mg',
    genericName: 'Chloroquine Phosphate',
    category: 'Antimalarial',
    dosageForm: 'Tablet',
    strength: '250mg (150mg base)',
    manufacturer: 'IDPL Government Depot',
    batchNumber: 'CHQ-2026-M3',
    expiryDate: new Date('2027-09-30'),
    facilityId: 'FAC-PHC-001',
    facilityName: 'Rampur PHC',
    stockQty: 180,
    minThreshold: 60,
    status: 'In Stock',
    unit: 'Strips (10 tabs)'
  },
  {
    id: 'MED-06',
    name: 'Artemether + Lumefantrine (ACT)',
    genericName: 'Artemether 80mg + Lumefantrine 480mg',
    category: 'Antimalarial Combination (ACT)',
    dosageForm: 'Tablet',
    strength: '80mg/480mg Forte',
    manufacturer: 'Cipla Govt Supply',
    batchNumber: 'ACT-2026-F1',
    expiryDate: new Date('2027-11-20'),
    facilityId: 'FAC-PHC-001',
    facilityName: 'Rampur PHC',
    stockQty: 95,
    minThreshold: 40,
    status: 'In Stock',
    unit: 'Blisters (6 tabs)'
  },
  {
    id: 'MED-07',
    name: 'Metformin 500mg (Sustained Release)',
    genericName: 'Metformin Hydrochloride SR',
    category: 'Oral Hypoglycemic / Diabetes',
    dosageForm: 'Tablet',
    strength: '500mg SR',
    manufacturer: 'Sun Pharma Healthcare Supply',
    batchNumber: 'MET-2026-G7',
    expiryDate: new Date('2027-04-10'),
    facilityId: 'FAC-CHC-001',
    facilityName: 'Bilari CHC',
    stockQty: 680,
    minThreshold: 300,
    status: 'In Stock',
    unit: 'Strips (10 tabs)'
  },
  {
    id: 'MED-08',
    name: 'Amlodipine 5mg',
    genericName: 'Amlodipine Besylate',
    category: 'Antihypertensive / Calcium Channel Blocker',
    dosageForm: 'Tablet',
    strength: '5mg',
    manufacturer: 'Torrent Pharmaceuticals Depot',
    batchNumber: 'AML-2026-H9',
    expiryDate: new Date('2027-06-18'),
    facilityId: 'FAC-PHC-001',
    facilityName: 'Rampur PHC',
    stockQty: 340,
    minThreshold: 100,
    status: 'In Stock',
    unit: 'Strips (10 tabs)'
  },
  {
    id: 'MED-09',
    name: 'Iron & Folic Acid (IFA Red Tablet)',
    genericName: 'Ferrous Sulphate 100mg + Folic Acid 0.5mg',
    category: 'Maternal Anemia Prophylaxis',
    dosageForm: 'Sugar Coated Tablet',
    strength: '100mg elemental iron',
    manufacturer: 'National Health Mission Depot',
    batchNumber: 'IFA-2026-J3',
    expiryDate: new Date('2027-01-30'),
    facilityId: 'FAC-PHC-001',
    facilityName: 'Rampur PHC',
    stockQty: 80,
    minThreshold: 250,
    status: 'Low Stock',
    unit: 'Strips (10 tabs)'
  },
  {
    id: 'MED-10',
    name: 'Ciprofloxacin 500mg',
    genericName: 'Ciprofloxacin Hydrochloride',
    category: 'Fluoroquinolone Antibiotic',
    dosageForm: 'Tablet',
    strength: '500mg',
    manufacturer: 'Alkem Laboratories Depot',
    batchNumber: 'CIP-2026-K5',
    expiryDate: new Date('2027-03-25'),
    facilityId: 'FAC-PHC-001',
    facilityName: 'Rampur PHC',
    stockQty: 110,
    minThreshold: 50,
    status: 'In Stock',
    unit: 'Strips (10 tabs)'
  },
  {
    id: 'MED-11',
    name: 'Cetirizine 10mg',
    genericName: 'Cetirizine Dihydrochloride',
    category: 'Antihistaminic / Antiallergy',
    dosageForm: 'Tablet',
    strength: '10mg',
    manufacturer: 'Dr. Reddy’s Laboratories Supply',
    batchNumber: 'CTZ-2026-L2',
    expiryDate: new Date('2027-07-14'),
    facilityId: 'FAC-PHC-001',
    facilityName: 'Rampur PHC',
    stockQty: 290,
    minThreshold: 80,
    status: 'In Stock',
    unit: 'Strips (10 tabs)'
  },
  {
    id: 'MED-12',
    name: 'Anti-Snake Venom (ASV Polyvalent Vials)',
    genericName: 'Polyvalent Snake Antivenom IP',
    category: 'Emergency Antidote',
    dosageForm: 'Lyophilized Powder Vial',
    strength: '10ml Reconstituted',
    manufacturer: 'Haffkine Biopharmaceutical Corporation',
    batchNumber: 'ASV-2026-X1',
    expiryDate: new Date('2026-11-30'),
    facilityId: 'FAC-CHC-001',
    facilityName: 'Bilari CHC',
    stockQty: 6,
    minThreshold: 15,
    status: 'Low Stock',
    unit: 'Vials'
  },
  {
    id: 'MED-13',
    name: 'Tetanus Toxoid (TT Injection 0.5ml)',
    genericName: 'Tetanus Vaccine Adsorbed IP',
    category: 'Vaccine / Immunoprophylaxis',
    dosageForm: 'Single Dose Ampoule',
    strength: '0.5ml (>= 40 IU)',
    manufacturer: 'Serum Institute of India',
    batchNumber: 'TT-2026-T9',
    expiryDate: new Date('2027-08-15'),
    facilityId: 'FAC-DH-001',
    facilityName: 'Moradabad District Hospital',
    stockQty: 450,
    minThreshold: 100,
    status: 'In Stock',
    unit: 'Ampoules'
  },
  {
    id: 'MED-14',
    name: 'Injectable Oxytocin 5 IU/ml',
    genericName: 'Synthetic Oxytocin Injection IP',
    category: 'Uterotonic / Maternal Emergency',
    dosageForm: 'Injection Ampoule',
    strength: '5 IU / 1ml',
    manufacturer: 'Karnataka Antibiotics (KAPL)',
    batchNumber: 'OXY-2026-O4',
    expiryDate: new Date('2026-10-15'),
    facilityId: 'FAC-CHC-001',
    facilityName: 'Bilari CHC',
    stockQty: 0,
    minThreshold: 20,
    status: 'Out of Stock',
    unit: 'Ampoules'
  },
  {
    id: 'MED-15',
    name: 'Expired Tetracycline 250mg',
    genericName: 'Tetracycline Hydrochloride',
    category: 'Antibiotic (Archived Batch)',
    dosageForm: 'Capsule',
    strength: '250mg',
    manufacturer: 'Government Depot Legacy',
    batchNumber: 'TET-2024-Z9',
    expiryDate: new Date('2025-01-01'), // Expired test sample
    facilityId: 'FAC-PHC-001',
    facilityName: 'Rampur PHC',
    stockQty: 25,
    minThreshold: 20,
    status: 'Expired',
    unit: 'Strips'
  }
];

const initialDiseaseMedicines = [
  // Malaria
  { diseaseId: 'DIS-101', medicineId: 'MED-05', diseaseName: 'Malaria', medicineName: 'Chloroquine Phosphate 250mg', standardDosage: '600mg base initially, followed by 300mg at 6h, 24h, 48h', standardFrequency: 'As per NVBDCP Protocol', standardDuration: '3 days', instructions: 'Take immediately after food to prevent nausea', isFirstLine: true, notes: 'First-line for P. vivax chloroquine sensitive malaria' },
  { diseaseId: 'DIS-101', medicineId: 'MED-06', diseaseName: 'Malaria', medicineName: 'Artemether + Lumefantrine (ACT)', standardDosage: '1 tablet (80/480mg)', standardFrequency: 'Twice daily', standardDuration: '3 days', instructions: 'Take with fatty meal or milk for absorption', isFirstLine: true, notes: 'First-line ACT for P. falciparum cases' },
  { diseaseId: 'DIS-101', medicineId: 'MED-01', diseaseName: 'Malaria', medicineName: 'Paracetamol 500mg', standardDosage: '500mg - 650mg', standardFrequency: 'Thrice daily as needed', standardDuration: '3-5 days', instructions: 'Take for fever > 100°F with plenty of fluids', isFirstLine: false, notes: 'Symptomatic antipyretic control' },

  // Acute Gastroenteritis
  { diseaseId: 'DIS-102', medicineId: 'MED-03', diseaseName: 'Acute Gastroenteritis / Dehydration', medicineName: 'Oral Rehydration Salts (ORS IP)', standardDosage: '1 liter solution (sip continuously)', standardFrequency: 'Frequent sips after every loose stool', standardDuration: '2-3 days until stools normalize', instructions: 'Mix one full packet in exactly 1 liter clean drinking water', isFirstLine: true, notes: 'Essential cornerstone of dehydration management' },
  { diseaseId: 'DIS-102', medicineId: 'MED-04', diseaseName: 'Acute Gastroenteritis / Dehydration', medicineName: 'Zinc Sulphate 20mg Dispersible', standardDosage: '20mg dispersible tab', standardFrequency: 'Once daily', standardDuration: '14 consecutive days', instructions: 'Dissolve in clean water or breast milk', isFirstLine: true, notes: 'Prevents recurrent diarrheal episodes for subsequent months' },
  { diseaseId: 'DIS-102', medicineId: 'MED-10', diseaseName: 'Acute Gastroenteritis / Dehydration', medicineName: 'Ciprofloxacin 500mg', standardDosage: '500mg', standardFrequency: 'Twice daily (BD)', standardDuration: '3-5 days', instructions: 'Drink ample fluids throughout the day', isFirstLine: false, notes: 'Indicated only in bacterial / invasive bloody dysentery' },

  // Dengue Fever
  { diseaseId: 'DIS-103', medicineId: 'MED-01', diseaseName: 'Dengue Fever', medicineName: 'Paracetamol 500mg', standardDosage: '500mg', standardFrequency: 'Every 6-8 hours (Max 3g/day)', standardDuration: '3-5 days', instructions: 'DO NOT prescribe NSAIDs (Aspirin/Ibuprofen) due to bleeding risk!', isFirstLine: true, notes: 'Only safe analgesic for Dengue pyrexia' },
  { diseaseId: 'DIS-103', medicineId: 'MED-03', diseaseName: 'Dengue Fever', medicineName: 'Oral Rehydration Salts (ORS IP)', standardDosage: '2-3 liters/day oral fluids', standardFrequency: 'Regular intervals', standardDuration: 'Critical phase (days 3-7)', instructions: 'Monitor daily hematocrit and platelet count', isFirstLine: true, notes: 'Prevent hypovolemic shock in plasma leakage phase' },

  // Type 2 Diabetes
  { diseaseId: 'DIS-104', medicineId: 'MED-07', diseaseName: 'Type 2 Diabetes Mellitus', medicineName: 'Metformin 500mg (Sustained Release)', standardDosage: '500mg SR tab', standardFrequency: 'Twice daily with principal meals', standardDuration: 'Continuous / Long term', instructions: 'Take with or immediately after meals to reduce GI upset', isFirstLine: true, notes: 'First-line biguanide for glycemic control' },

  // Essential Hypertension
  { diseaseId: 'DIS-105', medicineId: 'MED-08', diseaseName: 'Essential Hypertension', medicineName: 'Amlodipine 5mg', standardDosage: '5mg tab', standardFrequency: 'Once daily in the morning', standardDuration: 'Continuous / Long term', instructions: 'Take regularly at the same hour daily; monitor ankle swelling', isFirstLine: true, notes: 'Dihydropyridine calcium channel blocker' },

  // Upper Respiratory Tract Infection (URTI)
  { diseaseId: 'DIS-106', medicineId: 'MED-01', diseaseName: 'Upper Respiratory Tract Infection (URTI)', medicineName: 'Paracetamol 500mg', standardDosage: '500mg', standardFrequency: 'Twice or thrice daily as needed', standardDuration: '3-5 days', instructions: 'After food with warm water', isFirstLine: true, notes: 'Relieves fever and throat/body aches' },
  { diseaseId: 'DIS-106', medicineId: 'MED-11', diseaseName: 'Upper Respiratory Tract Infection (URTI)', medicineName: 'Cetirizine 10mg', standardDosage: '10mg tab', standardFrequency: 'Once daily at bedtime', standardDuration: '5 days', instructions: 'May cause mild drowsiness; avoid night driving', isFirstLine: true, notes: 'Controls rhinorrhea and sneezing' },
  { diseaseId: 'DIS-106', medicineId: 'MED-02', diseaseName: 'Upper Respiratory Tract Infection (URTI)', medicineName: 'Amoxicillin 500mg', standardDosage: '500mg capsule', standardFrequency: 'Thrice daily (TDS)', standardDuration: '5 days', instructions: 'Complete full course even if symptoms improve', isFirstLine: false, notes: 'Indicated for secondary bacterial sinusitis or tonsillitis' },

  // Iron Deficiency Anemia
  { diseaseId: 'DIS-107', medicineId: 'MED-09', diseaseName: 'Iron Deficiency Anemia (Maternal / General)', medicineName: 'Iron & Folic Acid (IFA Red Tablet)', standardDosage: '1 tablet daily', standardFrequency: 'Once daily', standardDuration: '100 days minimum', instructions: 'Take with lemon water or Vitamin C; do not take with tea or milk', isFirstLine: true, notes: 'Anemia Mukt Bharat national protocol standard' }
];

const initialPatients = [
  {
    id: 'PAT-IND-8921',
    name: 'Savitri Devi',
    age: 28,
    gender: 'Female',
    village: 'Shivpuri',
    ashaWorkerName: 'Kavita Singh (ASHA #42)',
    ashaWorkerContact: '+91-9871122334',
    guardianName: 'Ramesh Kumar (Husband)',
    phone: '+91-9870011223',
    sscCode: 'SSC-GJ-2026-108921',
    qrToken: 'SEC-QR-108921-7891',
    abhaId: 'ABHA-91-8273-1928-33',
    chiefComplaint: 'Severe lower abdominal pain during 3rd trimester pregnancy with elevated BP (150/100 mmHg)',
    symptomTags: ['Pregnancy Complication', 'Hypertension', 'Abdominal Pain'],
    vitals: { bp: '150/100', spo2: 97, temp: 98.6, pulse: 94, sugar: '110 mg/dL' },
    riskLevel: 'HIGH',
    triageCategory: 'RED_EMERGENCY',
    recommendedFacilityType: 'CHC or District Hospital (Obstetrics / Emergency)',
    bloodGroup: 'O+',
    knownAllergies: ['Sulfa Drugs'],
    chronicConditions: ['Gestational Hypertension'],
    currentHealthStatus: { condition: 'High Risk Pregnancy', summary: 'Under observation for preeclampsia', lastEvaluatedAt: new Date() },
    registrationDate: new Date(Date.now() - 2 * 60 * 60 * 1000)
  },
  {
    id: 'PAT-IND-7391',
    name: 'Aarav Sharma (Child)',
    age: 4,
    gender: 'Male',
    village: 'Rampur',
    ashaWorkerName: 'Meena Sharma (ASHA #18)',
    ashaWorkerContact: '+91-9871122335',
    guardianName: 'Pooja Sharma (Mother)',
    phone: '+91-9870011224',
    sscCode: 'SSC-GJ-2026-207391',
    qrToken: 'SEC-QR-207391-4412',
    abhaId: 'ABHA-91-4412-8871-09',
    chiefComplaint: 'High fever for 3 days with persistent vomiting, diarrhea and lethargy',
    symptomTags: ['Pediatric Fever', 'Vomiting', 'Lethargy', 'Gastroenteritis'],
    vitals: { bp: '95/60', spo2: 94, temp: 102.4, pulse: 128, sugar: 'Normal' },
    riskLevel: 'MODERATE',
    triageCategory: 'YELLOW_PRIORITY',
    recommendedFacilityType: 'PHC or CHC with Pediatrician',
    bloodGroup: 'B+',
    knownAllergies: [],
    chronicConditions: [],
    currentHealthStatus: { condition: 'Febrile Pediatric Illness', summary: 'Receiving ORS + Zinc hydration therapy', lastEvaluatedAt: new Date() },
    registrationDate: new Date(Date.now() - 5 * 60 * 60 * 1000)
  },
  {
    id: 'PAT-IND-4102',
    name: 'Ram Singh',
    age: 58,
    gender: 'Male',
    village: 'Fatehpur',
    ashaWorkerName: 'Sunita Devi (ASHA #09)',
    ashaWorkerContact: '+91-9871122336',
    guardianName: 'Self',
    phone: '+91-9870011225',
    sscCode: 'SSC-GJ-2026-304102',
    qrToken: 'SEC-QR-304102-1029',
    abhaId: 'ABHA-91-1029-3847-56',
    chiefComplaint: 'Sudden retrosternal chest pain radiating to left arm with breathlessness',
    symptomTags: ['Chest Pain', 'Shortness of Breath', 'Suspected Cardiac Event'],
    vitals: { bp: '168/104', spo2: 89, temp: 98.4, pulse: 112, sugar: '178 mg/dL' },
    riskLevel: 'CRITICAL',
    triageCategory: 'RED_EMERGENCY',
    recommendedFacilityType: 'District Hospital / Trauma & Cardiology Unit',
    bloodGroup: 'A+',
    knownAllergies: ['Penicillin'],
    chronicConditions: ['Hypertension', 'Type 2 Diabetes'],
    currentHealthStatus: { condition: 'Critical Cardiac Attention', summary: 'Referred to District Hospital via 108 Emergency', lastEvaluatedAt: new Date() },
    registrationDate: new Date(Date.now() - 30 * 60 * 1000)
  },
  {
    id: 'PAT-IND-1044',
    name: 'Kavita Bai',
    age: 34,
    gender: 'Female',
    village: 'Rampur',
    ashaWorkerName: 'Kavita Singh (ASHA #42)',
    ashaWorkerContact: '+91-9871122334',
    guardianName: 'Dinesh Patel',
    phone: '+91-9870011226',
    sscCode: 'SSC-GJ-2026-401044',
    qrToken: 'SEC-QR-401044-8831',
    abhaId: 'ABHA-91-8831-2947-11',
    chiefComplaint: 'Intermittent chills with high evening fever, severe headache and joint pain for 4 days',
    symptomTags: ['Fever', 'Chills', 'Suspected Malaria'],
    vitals: { bp: '118/76', spo2: 98, temp: 101.8, pulse: 88, sugar: '92 mg/dL' },
    riskLevel: 'MODERATE',
    triageCategory: 'YELLOW_PRIORITY',
    recommendedFacilityType: 'Rampur PHC (Malaria Diagnostics Available)',
    bloodGroup: 'B+',
    knownAllergies: [],
    chronicConditions: ['Mild Anemia'],
    currentHealthStatus: { condition: 'Malaria Under Pharmacotherapy', summary: 'Tested positive for P. Vivax on Rapid Diagnostic Kit', lastEvaluatedAt: new Date() },
    registrationDate: new Date(Date.now() - 24 * 60 * 60 * 1000)
  }
];

const initialPrescriptions = [
  {
    prescriptionId: 'RX-2026-104401',
    patientId: 'PAT-IND-1044',
    patientName: 'Kavita Bai',
    patientAge: 34,
    patientGender: 'Female',
    patientPhone: '+91-9870011226',
    doctorId: 'DOC-IND-101',
    doctorName: 'Dr. Rajesh Verma',
    facilityId: 'FAC-PHC-001',
    facilityName: 'Rampur Primary Health Centre (PHC)',
    diagnosis: 'Malaria (Plasmodium Vivax Confirmed by RDT)',
    diseaseId: 'DIS-101',
    clinicalNotes: 'Rapid Diagnostic Blood Kit positive for P. Vivax. Start NVBDCP Chloroquine regimen immediately. Advised rest and bed nets.',
    medicines: [
      {
        medicineId: 'MED-05',
        medicineName: 'Chloroquine Phosphate 250mg',
        genericName: 'Chloroquine Phosphate',
        dosageForm: 'Tablet',
        dosage: '600mg base initially, 300mg at 6h, 24h, 48h',
        frequency: 'As per schedule',
        duration: '3 days',
        instructions: 'Take strictly after meals with water',
        prescribedQty: 10,
        dispensedQty: 10,
        status: 'Fully Dispensed',
        batchHistory: [{ batchNumber: 'CHQ-2026-M3', quantity: 10, dispensedAt: new Date(Date.now() - 12 * 60 * 60 * 1000), dispensedBy: 'Ramesh Pharmacist' }]
      },
      {
        medicineId: 'MED-01',
        medicineName: 'Paracetamol 500mg',
        genericName: 'Paracetamol',
        dosageForm: 'Tablet',
        dosage: '1 tab (500mg)',
        frequency: 'Thrice daily if fever > 100°F',
        duration: '5 days',
        instructions: 'After food',
        prescribedQty: 15,
        dispensedQty: 10,
        status: 'Partially Dispensed',
        batchHistory: [{ batchNumber: 'PCM-2026-A1', quantity: 10, dispensedAt: new Date(Date.now() - 12 * 60 * 60 * 1000), dispensedBy: 'Ramesh Pharmacist' }]
      }
    ],
    status: 'Partially Dispensed',
    prescribedAt: new Date(Date.now() - 14 * 60 * 60 * 1000),
    followUpDate: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000)
  },
  {
    prescriptionId: 'RX-2026-739101',
    patientId: 'PAT-IND-7391',
    patientName: 'Aarav Sharma (Child)',
    patientAge: 4,
    patientGender: 'Male',
    patientPhone: '+91-9870011224',
    doctorId: 'DOC-IND-101',
    doctorName: 'Dr. Rajesh Verma',
    facilityId: 'FAC-PHC-001',
    facilityName: 'Rampur Primary Health Centre (PHC)',
    diagnosis: 'Acute Gastroenteritis / Dehydration',
    diseaseId: 'DIS-102',
    clinicalNotes: 'Mild to moderate dehydration. Oral rehydration therapy initiated with Zinc supplementation.',
    medicines: [
      {
        medicineId: 'MED-03',
        medicineName: 'Oral Rehydration Salts (ORS IP)',
        genericName: 'WHO Standard ORS',
        dosageForm: 'Powder Sachet',
        dosage: '1 Sachet in 1 Litre Water',
        frequency: 'Frequent sips',
        duration: '3 days',
        instructions: 'Give continuously throughout the day',
        prescribedQty: 6,
        dispensedQty: 0,
        status: 'Pending',
        batchHistory: []
      },
      {
        medicineId: 'MED-04',
        medicineName: 'Zinc Sulphate 20mg Dispersible',
        genericName: 'Zinc Sulphate Monohydrate',
        dosageForm: 'Dispersible Tablet',
        dosage: '1 tab (20mg)',
        frequency: 'Once daily',
        duration: '14 days',
        instructions: 'Dissolve in a spoonful of boiled clean water',
        prescribedQty: 14,
        dispensedQty: 0,
        status: 'Pending',
        batchHistory: []
      }
    ],
    status: 'Prescribed',
    prescribedAt: new Date(Date.now() - 3 * 60 * 60 * 1000),
    followUpDate: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000)
  }
];

const initialStockTransactions = [
  {
    transactionId: 'TXN-IN-901101',
    type: 'IN',
    medicineId: 'MED-01',
    medicineName: 'Paracetamol 500mg',
    batchNumber: 'PCM-2026-A1',
    quantity: 500,
    previousQty: 0,
    newQty: 500,
    expiryDate: new Date('2027-08-31'),
    supplier: 'Karnataka Antibiotics (KAPL) Central Depot',
    userId: 'admin',
    userName: 'Medical Depot Officer',
    userRole: 'admin',
    facilityId: 'FAC-PHC-001',
    facilityName: 'Rampur PHC',
    timestamp: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000)
  },
  {
    transactionId: 'TXN-OUT-901102',
    type: 'OUT',
    medicineId: 'MED-01',
    medicineName: 'Paracetamol 500mg',
    batchNumber: 'PCM-2026-A1',
    quantity: 10,
    previousQty: 430,
    newQty: 420,
    expiryDate: new Date('2027-08-31'),
    patientId: 'PAT-IND-1044',
    patientName: 'Kavita Bai',
    prescriptionId: 'RX-2026-104401',
    dispensedBy: 'Ramesh Pharmacist',
    userId: 'pharmacist-01',
    userName: 'Ramesh Pharmacist',
    userRole: 'pharmacist',
    facilityId: 'FAC-PHC-001',
    facilityName: 'Rampur PHC',
    timestamp: new Date(Date.now() - 12 * 60 * 60 * 1000)
  }
];

const initialReferrals = [
  {
    id: 'REF-2026-0891',
    referralCode: 'GA-REF-891',
    patientId: 'PAT-IND-4102',
    patientName: 'Ram Singh',
    age: 58,
    gender: 'Male',
    village: 'Fatehpur',
    referringUnit: 'Shivpuri Health Sub-Centre',
    referringStaff: 'ANM Geeta Devi / ASHA Sunita',
    referredToFacilityId: 'FAC-DH-001',
    referredToFacilityName: 'Moradabad District Civil & Trauma Hospital',
    referralReason: 'Acute Coronary Syndrome / Suspected Myocardial Infarction. Low SpO2 (89%), ECG facility needed urgently.',
    provisionalDiagnosis: 'Severe Angina / Cardiac Emergency',
    priority: 'EMERGENCY_RED',
    status: 'In-Transit',
    initiatedAt: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
    transportArranged: '108 Ambulance Dispatched (Reg: UP-21-G-4402)',
    vitalsSnapshot: { bp: '168/104', spo2: 89, temp: 98.4, pulse: 112 },
    doctorHandoffNotes: 'Emergency oxygen 4L/min started at sub-centre. Aspirin 300mg administered sublingually.',
    timeline: [
      { time: '11:25 AM', stage: 'Triage Flagged (RED Alert)', by: 'ASHA Sunita' },
      { time: '11:28 AM', stage: '108 Ambulance Dispatch Alert Triggered', by: 'Automated Routing' },
      { time: '11:32 AM', stage: 'Referral Slip Generated & District Hospital Pre-Notified', by: 'System Engine' },
      { time: '11:42 AM', stage: 'Patient In-Transit (ETA 18 mins)', by: 'Ambulance GPS Telemetry' }
    ]
  },
  {
    id: 'REF-2026-0874',
    referralCode: 'GA-REF-874',
    patientId: 'PAT-IND-8921',
    patientName: 'Savitri Devi',
    age: 28,
    gender: 'Female',
    village: 'Shivpuri',
    referringUnit: 'Rampur Primary Health Centre',
    referringStaff: 'Dr. Rajesh Verma',
    referredToFacilityId: 'FAC-CHC-001',
    referredToFacilityName: 'Bilari Community Health Centre (CHC)',
    referralReason: 'High Risk Pregnancy (Preeclampsia signs, BP 150/100, requires continuous fetal monitoring and Gynecologist evaluation).',
    provisionalDiagnosis: 'Gestational Hypertension with Impending Eclampsia',
    priority: 'HIGH_YELLOW',
    status: 'Received',
    initiatedAt: new Date(Date.now() - 90 * 60 * 1000).toISOString(),
    transportArranged: 'Janani Shishu Suraksha (JSSK) Van',
    vitalsSnapshot: { bp: '150/100', spo2: 97, temp: 98.6, pulse: 94 },
    doctorHandoffNotes: 'Patient arrived at CHC triage. Dr. Priya Saxena (Gynecologist) assigned. Bed #07 allocated in Maternity ward.',
    timeline: [
      { time: '10:15 AM', stage: 'PHC Examination & Referral Slip Issued', by: 'Dr. Rajesh Verma' },
      { time: '10:35 AM', stage: 'JSSK Transport Boarded', by: 'ASHA Kavita Singh' },
      { time: '11:05 AM', stage: 'Arrival & QR Code Scanned at Bilari CHC', by: 'Nurse Duty Desk' },
      { time: '11:15 AM', stage: 'Doctor Evaluation Commenced', by: 'Dr. Priya Saxena' }
    ]
  }
];

const initialOutbreaks = [
  {
    disease: 'Vector Borne (Suspected Dengue / Malaria)',
    village: 'Rampur & Shivpuri Clusters',
    block: 'Kashipur',
    casesThisWeek: 26,
    trend: '+45% vs last week',
    status: 'ACTIVE_WATCH',
    recommendedAction: 'Deploy Larvicide spraying & conduct fever survey with RDT kits.',
    detectedDate: '2026-08-25'
  },
  {
    disease: 'Acute Diarrheal Disease (Waterborne)',
    village: 'Fatehpur Sector 3',
    block: 'Bilari',
    casesThisWeek: 18,
    trend: '+28% vs last week',
    status: 'INTERVENTION_TRIGGERED',
    recommendedAction: 'Chlorination of 4 community handpumps + ORS/Zinc distribution by ASHA team.',
    detectedDate: '2026-08-27'
  }
];

module.exports = {
  initialFacilities,
  initialDiseases,
  initialMedicines,
  initialDiseaseMedicines,
  initialPatients,
  initialPrescriptions,
  initialStockTransactions,
  initialReferrals,
  initialOutbreaks
};
