const mongoose = require('mongoose');

const AuditLogSchema = new mongoose.Schema({
  action: {
    type: String,
    required: true,
    index: true,
    enum: [
      'PATIENT_LOOKUP',
      'QR_LOOKUP',
      'PATIENT_RECORD_ACCESS',
      'PATIENT_REGISTER',
      'PATIENT_CREATE',
      'PATIENT_UPDATE',
      'DIAGNOSIS_CREATE',
      'DIAGNOSIS_UPDATE',
      'PRESCRIPTION_CREATE',
      'PRESCRIPTION_UPDATE',
      'REMINDER_CREATE',
      'REMINDER_UPDATE',
      'REMINDER_OTP_VERIFY',
      'REFERRAL_CREATE',
      'REFERRAL_UPDATE',
      'STOCK_IN',
      'STOCK_OUT',
      'STOCK_ADJUSTMENT',
      'MEDICINE_DISPENSE',
      'DOCTOR_CREATE',
      'STAFF_CREATE',
      'FACILITY_CREATE',
      'FACILITY_UPDATE',
      'ADMIN_CREATE_USER',
      'ADMIN_UPDATE_USER',
      'ADMIN_DELETE_USER',
      'ADMIN_CREATE_PATIENT',
      'ADMIN_UPDATE_PATIENT',
      'ADMIN_DELETE_PATIENT',
      'ADMIN_CREATE_FACILITY',
      'ADMIN_UPDATE_FACILITY',
      'ADMIN_DELETE_FACILITY',
      'ADMIN_CREATE_MEDICINE',
      'ADMIN_UPDATE_MEDICINE',
      'ADMIN_DELETE_MEDICINE',
      'ADMIN_DELETE_RECORD',
      'ADMIN_DELETE_PRESCRIPTION',
      'ADMIN_DELETE_REFERRAL',
      'ADMIN_PURGE_COLLECTION'
    ]
  },
  userId: { type: String, default: 'anonymous', index: true },
  userName: { type: String, default: 'System User' },
  userRole: { type: String, default: 'unspecified', index: true },
  patientId: { type: String, default: '', index: true },
  resource: { type: String, default: '' },
  details: { type: mongoose.Schema.Types.Mixed, default: {} },
  status: { type: String, enum: ['SUCCESS', 'FAILURE', 'DENIED'], default: 'SUCCESS', index: true },
  ip: { type: String, default: '127.0.0.1' },
  timestamp: { type: Date, default: Date.now, index: true }
}, { timestamps: true });

module.exports = mongoose.models.AuditLog || mongoose.model('AuditLog', AuditLogSchema);
